import { Scenario } from "./types";
import { getLatestPriceRecord } from "./price-history";

function benchmark(slug: string) {
  const record = getLatestPriceRecord(slug);
  if (!record) throw new Error(`Missing benchmark: ${slug}`);
  return { currentItemPriceUSD: record.newUSD, shortDescription: record.definition };
}

export const defaultScenario: Scenario = {
  slug: "tesla-model-3",
  itemName: "Tesla Model 3",
  shortDescription: "New from Tesla",
  category: "Vehicle",
  icon: "Car",
  image: "/scenarios/tesla-model-3.png",
  imageAlternates: ["/scenarios/alternates/tesla-model-3-card.png"],
  currentItemPriceUSD: 41000,
  currencyCode: "USD",
  currentBTCPriceUSD: 80000,
  years: 5,
  itemInflationRate: 4,
  btcGrowthRate: 15,
  purchaseType: "one-time",
};

export const scenarios: Scenario[] = [
  defaultScenario,
  {
    slug: "median-us-house",
    itemName: "Median U.S. house",
    ...benchmark("median-us-house"),
    category: "Housing",
    icon: "Home",
    image: "/scenarios/median-us-house.png",
    imageAlternates: ["/scenarios/alternates/median-us-house-card.png"],
    currentBTCPriceUSD: 80000,
    years: 10,
    itemInflationRate: 3.5,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "rent",
    itemName: "Rent",
    ...benchmark("rent"),
    category: "Monthly expense",
    icon: "Building2",
    image: "/scenarios/rent.png",
    currentBTCPriceUSD: 80000,
    years: 5,
    itemInflationRate: 4.5,
    btcGrowthRate: 15,
    purchaseType: "monthly",
  },
  {
    slug: "elder-care",
    itemName: "Elder care",
    ...benchmark("elder-care"),
    category: "Care",
    icon: "Heart",
    image: "/scenarios/elder-care.png",
    imageAlternates: ["/scenarios/alternates/elder-care-room.png"],
    currentBTCPriceUSD: 80000,
    years: 5,
    itemInflationRate: 8.1,
    btcGrowthRate: 15,
    purchaseType: "monthly",
  },
  {
    slug: "childcare",
    itemName: "Childcare",
    ...benchmark("childcare"),
    category: "Family",
    icon: "Users",
    currentBTCPriceUSD: 80000,
    years: 5,
    itemInflationRate: 5.5,
    btcGrowthRate: 15,
    purchaseType: "monthly",
  },
  {
    slug: "college-tuition",
    itemName: "College tuition",
    ...benchmark("college-tuition"),
    category: "Education",
    icon: "GraduationCap",
    image: "/scenarios/college-tuition.png",
    currentBTCPriceUSD: 80000,
    years: 10,
    itemInflationRate: 5,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "wedding",
    itemName: "Wedding",
    ...benchmark("wedding"),
    category: "Life event",
    icon: "Sparkles",
    currentBTCPriceUSD: 80000,
    years: 4,
    itemInflationRate: 4.5,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "vacation",
    itemName: "Vacation",
    shortDescription: "One-week trip for two",
    category: "Travel",
    icon: "Plane",
    image: "/scenarios/vacation.png",
    currentItemPriceUSD: 5242,
    currentBTCPriceUSD: 80000,
    years: 3,
    itemInflationRate: 5,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "laptop",
    itemName: "Laptop",
    shortDescription: "Quality 15-inch laptop",
    category: "Technology",
    icon: "Laptop",
    image: "/scenarios/laptop.png",
    currentItemPriceUSD: 1299,
    currentBTCPriceUSD: 80000,
    years: 4,
    itemInflationRate: 2,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "dividend-stock-portfolio",
    itemName: "Dividend stock portfolio",
    shortDescription: "Income portfolio target",
    category: "Savings goal",
    icon: "LineChart",
    currentItemPriceUSD: 250000,
    currentBTCPriceUSD: 80000,
    years: 8,
    itemInflationRate: 3,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "starting-a-business",
    itemName: "Starting a business",
    shortDescription: "Startup capital reserve",
    category: "Work",
    icon: "BriefcaseBusiness",
    currentItemPriceUSD: 50000,
    currentBTCPriceUSD: 80000,
    years: 5,
    itemInflationRate: 4,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
  {
    slug: "emergency-fund",
    itemName: "Emergency fund",
    shortDescription: "Six-month cash buffer",
    category: "Safety",
    icon: "ShieldCheck",
    currentItemPriceUSD: 30000,
    currentBTCPriceUSD: 80000,
    years: 5,
    itemInflationRate: 3.5,
    btcGrowthRate: 15,
    purchaseType: "one-time",
  },
];

export function getScenario(slug: string) {
  return scenarios.find((scenario) => scenario.slug === slug);
}
